import React, { useMemo, useState } from 'react';

type BppOperationType = 'DRILL' | 'CUT' | 'GROOVE' | 'UNKNOWN';

interface BppOperation {
  lineNumber: number;
  raw: string;
  type: BppOperationType;
  params: Record<string, string | number>;
}

interface VectorPoint {
  id: string;
  x: number;
  y: number;
  type: BppOperationType;
  diameter: number;
}

const parseValue = (value: string): string | number => {
  const normalized = value.replace(',', '.').trim();
  const asNumber = Number(normalized);
  return Number.isFinite(asNumber) ? asNumber : value.trim();
};

const normalizeKey = (value: string) => value.trim().toUpperCase();

const classifyOperation = (line: string): BppOperationType => {
  const upper = line.toUpperCase();
  if (upper.includes('DRILL') || upper.includes('BORE')) return 'DRILL';
  if (upper.includes('CUT') || upper.includes('MILL')) return 'CUT';
  if (upper.includes('GROOVE') || upper.includes('SLOT')) return 'GROOVE';
  return 'UNKNOWN';
};

const parseBpp = (content: string): BppOperation[] => {
  const lines = content
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && !line.startsWith('#') && !line.startsWith(';'));

  return lines.map((line, index) => {
    const params: Record<string, string | number> = {};
    const tokens = line.split(/[\s,]+/);

    tokens.forEach((token) => {
      const [rawKey, rawValue] = token.split('=');
      if (!rawKey || rawValue === undefined) return;
      params[normalizeKey(rawKey)] = parseValue(rawValue);
    });

    return {
      lineNumber: index + 1,
      raw: line,
      type: classifyOperation(line),
      params,
    };
  });
};

const toBhx50 = (operations: BppOperation[]): string => {
  const header = [
    '; BHX50 CONVERSION FILE',
    '; Generated by BPP converter',
    `; Operations: ${operations.length}`,
    '',
  ];

  const body = operations.map((op, index) => {
    const x = Number(op.params.X ?? 0);
    const y = Number(op.params.Y ?? 0);
    const z = Number(op.params.Z ?? 0);
    const depth = Number(op.params.DEPTH ?? op.params.D ?? 0);
    const diameter = Number(op.params.DIAMETER ?? op.params.DIA ?? 0);

    return [
      `N${(index + 1).toString().padStart(4, '0')}`,
      `TYPE=${op.type}`,
      `X=${x.toFixed(3)}`,
      `Y=${y.toFixed(3)}`,
      `Z=${z.toFixed(3)}`,
      `DEPTH=${depth.toFixed(3)}`,
      `DIA=${diameter.toFixed(3)}`,
      `RAW=${op.raw}`,
    ].join(' | ');
  });

  return [...header, ...body].join('\n');
};

const getNumericParam = (params: Record<string, string | number>, ...keys: string[]): number | null => {
  for (const key of keys) {
    const value = params[key];
    if (value === undefined) continue;
    const numericValue = Number(value);
    if (Number.isFinite(numericValue)) return numericValue;
  }
  return null;
};

const buildVectorPoints = (operations: BppOperation[]): VectorPoint[] =>
  operations
    .map((op, index) => {
      const x = getNumericParam(op.params, 'X', 'XP', 'XE');
      const y = getNumericParam(op.params, 'Y', 'YP', 'YE');
      if (x === null || y === null) return null;

      return {
        id: `${op.lineNumber}-${index}`,
        x,
        y,
        type: op.type,
        diameter: getNumericParam(op.params, 'DIAMETER', 'DIA', 'D') ?? 5,
      };
    })
    .filter((point): point is VectorPoint => point !== null);

const OPERATION_COLORS: Record<BppOperationType, string> = {
  DRILL: '#2563eb',
  CUT: '#059669',
  GROOVE: '#ea580c',
  UNKNOWN: '#6b7280',
};

const downloadFile = (filename: string, content: string) => {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
};

const App: React.FC = () => {
  const [fileName, setFileName] = useState('');
  const [rawBpp, setRawBpp] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [viewMode, setViewMode] = useState<'table' | 'vector'>('vector');

  const operations = useMemo(() => parseBpp(rawBpp), [rawBpp]);
  const bhxOutput = useMemo(() => toBhx50(operations), [operations]);
  const vectorPoints = useMemo(() => buildVectorPoints(operations), [operations]);

  const vectorBounds = useMemo(() => {
    if (vectorPoints.length === 0) return null;
    const minX = Math.min(...vectorPoints.map((point) => point.x));
    const maxX = Math.max(...vectorPoints.map((point) => point.x));
    const minY = Math.min(...vectorPoints.map((point) => point.y));
    const maxY = Math.max(...vectorPoints.map((point) => point.y));
    const padding = 20;

    return {
      minX,
      maxX,
      minY,
      maxY,
      width: Math.max(100, maxX - minX),
      height: Math.max(100, maxY - minY),
      viewBox: `${minX - padding} ${minY - padding} ${Math.max(100, maxX - minX) + padding * 2} ${Math.max(100, maxY - minY) + padding * 2}`,
    };
  }, [vectorPoints]);

  const loadFile = async (file: File) => {
    try {
      const text = await file.text();
      setRawBpp(text);
      setFileName(file.name);
      setError(null);
    } catch (e) {
      setError('No se pudo leer el archivo .bpp');
    }
  };

  return (
    <main style={{ fontFamily: 'Inter, sans-serif', maxWidth: 1100, margin: '0 auto', padding: 24 }}>
      <h1 style={{ marginBottom: 8 }}>Conversor .BPP → BHX50</h1>
      <p style={{ marginTop: 0, color: '#444' }}>
        Sube tu archivo de mecanizado <strong>.bpp</strong>, revisa las operaciones detectadas y exporta un archivo de salida para BHX50.
      </p>

      <section style={{ display: 'grid', gap: 16, gridTemplateColumns: '1fr 1fr' }}>
        <div style={{ border: '1px solid #ddd', borderRadius: 10, padding: 16 }}>
          <h2 style={{ marginTop: 0 }}>Entrada BPP</h2>
          <input
            type="file"
            accept=".bpp,.txt"
            onChange={(event) => {
              const file = event.target.files?.[0];
              if (file) {
                void loadFile(file);
              }
            }}
          />
          <p style={{ color: '#666', fontSize: 14 }}>{fileName ? `Archivo cargado: ${fileName}` : 'Aún no has cargado archivo.'}</p>
          <textarea
            value={rawBpp}
            onChange={(event) => setRawBpp(event.target.value)}
            placeholder="También puedes pegar aquí el contenido BPP"
            style={{ width: '100%', minHeight: 320, resize: 'vertical' }}
          />
        </div>

        <div style={{ border: '1px solid #ddd', borderRadius: 10, padding: 16 }}>
          <h2 style={{ marginTop: 0 }}>Salida BHX50</h2>
          <button
            onClick={() => downloadFile((fileName || 'programa').replace(/\.bpp$/i, '') + '.bhx', bhxOutput)}
            disabled={!rawBpp.trim()}
            style={{ marginBottom: 12 }}
          >
            Descargar .bhx
          </button>
          <textarea readOnly value={bhxOutput} style={{ width: '100%', minHeight: 320, resize: 'vertical', background: '#fafafa' }} />
        </div>
      </section>

      <section style={{ marginTop: 20, border: '1px solid #ddd', borderRadius: 10, padding: 16 }}>
        <h2 style={{ marginTop: 0 }}>Operaciones detectadas ({operations.length})</h2>
        {error && <p style={{ color: '#b00020' }}>{error}</p>}
        <div style={{ display: 'flex', gap: 8, marginBottom: 12 }}>
          <button onClick={() => setViewMode('vector')} style={{ background: viewMode === 'vector' ? '#111827' : '#f3f4f6', color: viewMode === 'vector' ? 'white' : '#111827' }}>
            Vista vectorial (planta)
          </button>
          <button onClick={() => setViewMode('table')} style={{ background: viewMode === 'table' ? '#111827' : '#f3f4f6', color: viewMode === 'table' ? 'white' : '#111827' }}>
            Vista tabla
          </button>
        </div>

        {viewMode === 'vector' ? (
          <div>
            <p style={{ marginTop: 0, color: '#4b5563' }}>
              Planta 2D basada en coordenadas X/Y detectadas en el archivo BPP.
            </p>
            {vectorBounds ? (
              <svg viewBox={vectorBounds.viewBox} style={{ width: '100%', height: 420, border: '1px solid #e5e7eb', background: '#f9fafb' }}>
                <rect
                  x={vectorBounds.minX}
                  y={vectorBounds.minY}
                  width={vectorBounds.width}
                  height={vectorBounds.height}
                  fill="none"
                  stroke="#9ca3af"
                  strokeDasharray="5 4"
                />
                {vectorPoints.map((point) => (
                  <g key={point.id}>
                    <circle cx={point.x} cy={point.y} r={Math.max(2, point.diameter / 2)} fill={OPERATION_COLORS[point.type]} fillOpacity={0.75} />
                    <title>{`Línea ${point.id} · ${point.type} · X:${point.x} Y:${point.y}`}</title>
                  </g>
                ))}
              </svg>
            ) : (
              <p style={{ color: '#6b7280' }}>No se encontraron coordenadas X/Y para dibujar la planta vectorial.</p>
            )}
            <div style={{ display: 'flex', gap: 16, marginTop: 12, flexWrap: 'wrap' }}>
              {Object.entries(OPERATION_COLORS).map(([type, color]) => (
                <span key={type} style={{ display: 'inline-flex', alignItems: 'center', gap: 6, color: '#374151', fontSize: 13 }}>
                  <span style={{ width: 10, height: 10, borderRadius: 999, background: color, display: 'inline-block' }} />
                  {type}
                </span>
              ))}
            </div>
          </div>
        ) : (
          <>
            <table style={{ width: '100%', borderCollapse: 'collapse' }}>
              <thead>
                <tr style={{ textAlign: 'left', borderBottom: '1px solid #eee' }}>
                  <th>#</th>
                  <th>Tipo</th>
                  <th>X</th>
                  <th>Y</th>
                  <th>Z</th>
                  <th>Profundidad</th>
                  <th>Diámetro</th>
                </tr>
              </thead>
              <tbody>
                {operations.slice(0, 20).map((op) => (
                  <tr key={`${op.lineNumber}-${op.raw}`} style={{ borderBottom: '1px solid #f1f1f1' }}>
                    <td>{op.lineNumber}</td>
                    <td>{op.type}</td>
                    <td>{String(op.params.X ?? '-')}</td>
                    <td>{String(op.params.Y ?? '-')}</td>
                    <td>{String(op.params.Z ?? '-')}</td>
                    <td>{String(op.params.DEPTH ?? op.params.D ?? '-')}</td>
                    <td>{String(op.params.DIAMETER ?? op.params.DIA ?? '-')}</td>
                  </tr>
                ))}
              </tbody>
            </table>
            {operations.length > 20 && <p style={{ color: '#666' }}>Mostrando 20 de {operations.length} operaciones.</p>}
          </>
        )}
      </section>
    </main>
  );
};

export default App;
