import React, { useMemo, useState } from 'react';

type BppOperationType = 'DRILL' | 'CUT' | 'GROOVE' | 'UNKNOWN';

interface BppOperation {
  lineNumber: number;
  raw: string;
  type: BppOperationType;
  params: Record<string, string | number>;
}

const parseValue = (value: string): string | number => {
  const normalized = value.replace(',', '.').trim();
  const asNumber = Number(normalized);
  return Number.isFinite(asNumber) ? asNumber : value.trim();
};

const normalizeKey = (value: string) => value.trim().toUpperCase();

const classifyOperation = (line: string): BppOperationType => {
  const upper = line.toUpperCase();
  if (upper.includes('DRILL') || upper.includes('BORE')) return 'DRILL';
  if (upper.includes('CUT') || upper.includes('MILL')) return 'CUT';
  if (upper.includes('GROOVE') || upper.includes('SLOT')) return 'GROOVE';
  return 'UNKNOWN';
};

const parseBpp = (content: string): BppOperation[] => {
  const lines = content
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && !line.startsWith('#') && !line.startsWith(';'));

  return lines.map((line, index) => {
    const params: Record<string, string | number> = {};
    const tokens = line.split(/[\s,]+/);

    tokens.forEach((token) => {
      const [rawKey, rawValue] = token.split('=');
      if (!rawKey || rawValue === undefined) return;
      params[normalizeKey(rawKey)] = parseValue(rawValue);
    });

    return {
      lineNumber: index + 1,
      raw: line,
      type: classifyOperation(line),
      params,
    };
  });
};

const toBhx50 = (operations: BppOperation[]): string => {
  const header = [
    '; BHX50 CONVERSION FILE',
    '; Generated by BPP converter',
    `; Operations: ${operations.length}`,
    '',
  ];

  const body = operations.map((op, index) => {
    const x = Number(op.params.X ?? 0);
    const y = Number(op.params.Y ?? 0);
    const z = Number(op.params.Z ?? 0);
    const depth = Number(op.params.DEPTH ?? op.params.D ?? 0);
    const diameter = Number(op.params.DIAMETER ?? op.params.DIA ?? 0);

    return [
      `N${(index + 1).toString().padStart(4, '0')}`,
      `TYPE=${op.type}`,
      `X=${x.toFixed(3)}`,
      `Y=${y.toFixed(3)}`,
      `Z=${z.toFixed(3)}`,
      `DEPTH=${depth.toFixed(3)}`,
      `DIA=${diameter.toFixed(3)}`,
      `RAW=${op.raw}`,
    ].join(' | ');
  });

  return [...header, ...body].join('\n');
};

const downloadFile = (filename: string, content: string) => {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
};

const App: React.FC = () => {
  const [fileName, setFileName] = useState('');
  const [rawBpp, setRawBpp] = useState('');
  const [error, setError] = useState<string | null>(null);

  const operations = useMemo(() => parseBpp(rawBpp), [rawBpp]);
  const bhxOutput = useMemo(() => toBhx50(operations), [operations]);

  const loadFile = async (file: File) => {
    try {
      const text = await file.text();
      setRawBpp(text);
      setFileName(file.name);
      setError(null);
    } catch (e) {
      setError('No se pudo leer el archivo .bpp');
    }
  };

  return (
    <main style={{ fontFamily: 'Inter, sans-serif', maxWidth: 1100, margin: '0 auto', padding: 24 }}>
      <h1 style={{ marginBottom: 8 }}>Conversor .BPP → BHX50</h1>
      <p style={{ marginTop: 0, color: '#444' }}>
        Sube tu archivo de mecanizado <strong>.bpp</strong>, revisa las operaciones detectadas y exporta un archivo de salida para BHX50.
      </p>

      <section style={{ display: 'grid', gap: 16, gridTemplateColumns: '1fr 1fr' }}>
        <div style={{ border: '1px solid #ddd', borderRadius: 10, padding: 16 }}>
          <h2 style={{ marginTop: 0 }}>Entrada BPP</h2>
          <input
            type="file"
            accept=".bpp,.txt"
            onChange={(event) => {
              const file = event.target.files?.[0];
              if (file) {
                void loadFile(file);
              }
            }}
          />
          <p style={{ color: '#666', fontSize: 14 }}>{fileName ? `Archivo cargado: ${fileName}` : 'Aún no has cargado archivo.'}</p>
          <textarea
            value={rawBpp}
            onChange={(event) => setRawBpp(event.target.value)}
            placeholder="También puedes pegar aquí el contenido BPP"
            style={{ width: '100%', minHeight: 320, resize: 'vertical' }}
          />
        </div>

        <div style={{ border: '1px solid #ddd', borderRadius: 10, padding: 16 }}>
          <h2 style={{ marginTop: 0 }}>Salida BHX50</h2>
          <button
            onClick={() => downloadFile((fileName || 'programa').replace(/\.bpp$/i, '') + '.bhx', bhxOutput)}
            disabled={!rawBpp.trim()}
            style={{ marginBottom: 12 }}
          >
            Descargar .bhx
          </button>
          <textarea readOnly value={bhxOutput} style={{ width: '100%', minHeight: 320, resize: 'vertical', background: '#fafafa' }} />
        </div>
      </section>

      <section style={{ marginTop: 20, border: '1px solid #ddd', borderRadius: 10, padding: 16 }}>
        <h2 style={{ marginTop: 0 }}>Operaciones detectadas ({operations.length})</h2>
        {error && <p style={{ color: '#b00020' }}>{error}</p>}
        <table style={{ width: '100%', borderCollapse: 'collapse' }}>
          <thead>
            <tr style={{ textAlign: 'left', borderBottom: '1px solid #eee' }}>
              <th>#</th>
              <th>Tipo</th>
              <th>X</th>
              <th>Y</th>
              <th>Z</th>
              <th>Profundidad</th>
              <th>Diámetro</th>
            </tr>
          </thead>
          <tbody>
            {operations.slice(0, 20).map((op) => (
              <tr key={`${op.lineNumber}-${op.raw}`} style={{ borderBottom: '1px solid #f1f1f1' }}>
                <td>{op.lineNumber}</td>
                <td>{op.type}</td>
                <td>{String(op.params.X ?? '-')}</td>
                <td>{String(op.params.Y ?? '-')}</td>
                <td>{String(op.params.Z ?? '-')}</td>
                <td>{String(op.params.DEPTH ?? op.params.D ?? '-')}</td>
                <td>{String(op.params.DIAMETER ?? op.params.DIA ?? '-')}</td>
              </tr>
            ))}
          </tbody>
        </table>
        {operations.length > 20 && <p style={{ color: '#666' }}>Mostrando 20 de {operations.length} operaciones.</p>}
      </section>
    </main>
  );
};

export default App;
